// SPDX-License-Identifier: GPL-3.0-only
// Copyright (C) 2026 MagicCards contributors

import {build,root} from '../scripts/build.mjs';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {pathToFileURL,fileURLToPath} from 'node:url';
import {resolve} from 'node:path';
import assert from 'node:assert/strict';
export async function runTests(){
  await build();
  const stamp=Date.now(),url=p=>pathToFileURL(resolve(root,p)).href+'?v='+stamp;
  const E=await import(url('dist/src/engine/engine.mjs')),C=await import(url('dist/src/content/compile.mjs')),B=await import(url('dist/src/bot/policy.mjs'));
  const raw=JSON.parse(await readFile(resolve(root,'dist/content.json'),'utf8')),content=C.validateContent(raw),results=[];
  const test=(name,fn)=>{try{fn();results.push({name,ok:true});}catch(e){results.push({name,ok:false,error:e.stack});}};
  const fixture=(extra={})=>E.loadFixture({presetId:'automatic_energy_v1',players:{p1:{pool:{'core:energy':20}},p2:{pool:{'core:energy':20}}},...extra},content);
  const find=(s,id)=>E.ref(Object.values(s.instances).find(x=>x.cardId===id));
  const exec=(s,c)=>{const r=E.execute(s,c);assert.ok(r.ok,JSON.stringify(r.error));return r.state;};
  const pass=s=>exec(s,{type:'PassPriority',actorId:s.priorityPlayerId});
  const resolveTop=s=>pass(pass(s));
  const cast=(s,id,targets={})=>exec(s,{type:'CastCard',actorId:s.priorityPlayerId,card:find(s,id),targets});
  test('RNG: контрольный вектор xorshift32',()=>{const x={rngState:1};assert.deepEqual(Array.from({length:5},()=>E.nextRandom(x)),[270369,67634689,2647435461,307599695,2398689233]);});
  test('Старт: две руки по 4, первый игрок из seed, seed 0 = 1',()=>{const s=E.createGame({},content,1);assert.equal(s.firstPlayerId,'p2');assert.equal(s.players.p1.hand.length,4);assert.equal(s.players.p2.deck.length,20);assert.equal(E.hashState(s),E.hashState(E.createGame({},content,0)));});
  test('Два паса переводят ровно один шаг',()=>{const s=E.createGame({},content,1);assert.equal(resolveTop(s).phase,'DRAW');});
  test('Первый игрок пропускает только первый добор',()=>{let s=E.createGame({},content,1);s=resolveTop(s);assert.equal(s.players.p2.hand.length,4);});
  test('Неверный приоритет: состояние, события и RNG неизменны',()=>{const s=fixture();const text=JSON.stringify(s);const r=E.execute(s,{type:'PassPriority',actorId:'p2'});assert.equal(r.error.code,'NOT_YOUR_PRIORITY');assert.equal(JSON.stringify(s),text);assert.equal(r.state,s);assert.deepEqual(r.events,[]);});
  test('После розыгрыша сохраняется приоритет; существо входит после 2 пасов',()=>{let s=fixture({hand:{p1:['core:recruit']}});s=cast(s,'core:recruit');assert.equal(s.priorityPlayerId,'p1');assert.equal(s.stack.length,1);s=resolveTop(s);assert.equal(Object.values(s.instances)[0].zone,'battlefield');});
  test('Контрответ: Искра → Отмена → Отмена, LIFO по одному элементу',()=>{let s=fixture({hand:{p1:['core:spark','core:counterspell'],p2:['core:counterspell']}});s=cast(s,'core:spark',{victim:{playerId:'p2'}});const spark=s.stack[0].itemId;s=pass(s);const enemy=E.ref(Object.values(s.instances).find(o=>o.cardId==='core:counterspell'&&o.ownerId==='p2'));s=exec(s,{type:'CastCard',actorId:'p2',card:enemy,targets:{victim:{itemId:spark}}});const counter=s.stack.at(-1).itemId;s=pass(s);s=cast(s,'core:counterspell',{victim:{itemId:counter}});s=resolveTop(s);assert.equal(s.stack.length,1);assert.equal(s.players.p2.health,20);s=resolveTop(s);assert.equal(s.players.p2.health,17);});
  test('Ответ лечением снимает фильтр Добивания',()=>{let s=fixture({hand:{p1:['core:execution'],p2:['core:mend']},board:{p2:[{cardId:'core:sentinel',markedDamage:1}]}});const r=find(s,'core:sentinel');s=cast(s,'core:execution',{victim:r});s=pass(s);s=cast(s,'core:mend',{victim:r});s=resolveTop(s);s=resolveTop(s);assert.equal(E.getObject(s,r).zone,'battlefield');assert.equal(s.events.at(-1).type,'resolution_ended');});
  test('Внутри frame урон→лечение спасает существо',()=>{const r=structuredClone(raw);r.cards.push({id:'test:save',name:'Тест',typeId:'types:instant',cost:{generic:0},targets:[{id:'victim',selector:'friendly_creature',count:1}],effects:[{type:'damage',target:{selected:'victim'},amount:5},{type:'heal',target:{selected:'victim'},amount:5}]});const c=C.validateContent(r);let s=E.loadFixture({board:{p1:['core:recruit']},hand:{p1:['test:save']}},c);const target=find(s,'core:recruit');s=cast(s,'test:save',{victim:target});s=resolveTop(s);assert.equal(E.getObject(s,target).zone,'battlefield');assert.equal(s.deaths.length,0);});
  test('Массовая смерть создаёт независимые триггеры',()=>{let s=fixture({hand:{p1:['core:ember_rain']},board:{p2:['core:ember_bearer','core:ember_bearer']}});s=resolveTop(cast(s,'core:ember_rain'));assert.equal(s.deaths.length,2);assert.equal(s.stack.length,2);s=resolveTop(resolveTop(s));assert.equal(s.players.p1.health,18);});
  test('Поле ограничено настройкой, не UI',()=>{const s=fixture({config:{presetId:'automatic_energy_v1',limits:{maxCreaturesPerPlayer:1}},board:{p1:['core:recruit']},hand:{p1:['core:sentinel']}});const r=E.execute(s,{type:'CastCard',actorId:'p1',card:find(s,'core:sentinel')});assert.equal(r.error.code,'BOARD_FULL');});
  test('Призывная задержка атаки; свежий защитник может блокировать',()=>{const s=fixture({phase:'DECLARE_ATTACKERS',board:{p1:[{cardId:'core:recruit',enteredTurn:5,controllerTurnEntered:3}]},combat:{combatId:'x',attackers:[],deaths:[]}});assert.equal(E.getLegalActions(s,'p1')[0].attackers.length,0);});
  test('Vigilance не поворачивает атакующего',()=>{let s=fixture({phase:'DECLARE_ATTACKERS',board:{p1:['core:sentinel']},combat:{combatId:'x',attackers:[],deaths:[]}});const a=find(s,'core:sentinel');s=exec(s,{type:'DeclareAttackers',actorId:'p1',attackers:[{attacker:a,defender:{playerId:'p2'}}]});assert.equal(E.getObject(s,a).tapped,false);});
  test('Незаблокированная атака наносит урон игроку',()=>{let s=fixture({phase:'DECLARE_ATTACKERS',board:{p1:['core:sentinel']},combat:{combatId:'x',attackers:[],deaths:[]}});s=exec(s,{type:'DeclareAttackers',actorId:'p1',attackers:[{attacker:find(s,'core:sentinel'),defender:{playerId:'p2'}}]});s=resolveTop(s);s=exec(s,{type:'DeclareBlockers',actorId:'p2',blockers:[]});s=resolveTop(s);assert.equal(s.players.p2.health,18);});
  test('Законный блок сохраняется после смерти блокирующего',()=>{let s=fixture({phase:'DECLARE_ATTACKERS',board:{p1:['core:sentinel'],p2:['core:recruit']},hand:{p1:['core:spark']},combat:{combatId:'x',attackers:[],deaths:[]}});const a=find(s,'core:sentinel'),b=find(s,'core:recruit');s=exec(s,{type:'DeclareAttackers',actorId:'p1',attackers:[{attacker:a,defender:{playerId:'p2'}}]});s=resolveTop(s);s=exec(s,{type:'DeclareBlockers',actorId:'p2',blockers:[{attacker:a,blocker:b}]});s=resolveTop(cast(s,'core:spark',{victim:b}));s=resolveTop(s);assert.equal(s.players.p2.health,20);});
  test('Полёт и призрачность: независимые ограничения AND',()=>{const s=fixture({board:{p1:['examples:spectral_drake'],p2:['examples:reach_guard','examples:spirit_guard']}});assert.equal(E.evaluateInteraction(s,'block',{attacker:find(s,'examples:spectral_drake'),blocker:find(s,'examples:reach_guard')}).allowed,false);assert.equal(E.evaluateInteraction(s,'block',{attacker:find(s,'examples:spectral_drake'),blocker:find(s,'examples:spirit_guard')}).allowed,true);});
  test('Аура: повторный пересчёт идемпотентен',()=>{const s=fixture({board:{p1:['examples:war_banner_source','core:recruit']}}),r=find(s,'core:recruit');const first=E.effectiveView(s);for(let i=0;i<10;i++)assert.deepEqual(E.effectiveView(s),first);assert.equal(first[r.instanceId+'@'+r.generation].attack,2);});
  test('Потеря ауры может привести к смерти без нового урона',()=>{let s=fixture({board:{p1:[{cardId:'core:recruit',markedDamage:2},{cardId:'examples:war_banner_source',markedDamage:1}]},hand:{p2:['core:execution']},activePlayerId:'p2',priorityPlayerId:'p2'});s=resolveTop(cast(s,'core:execution',{victim:find(s,'examples:war_banner_source')}));assert.equal(s.deaths.length,2);});
  test('Неоплачиваемая жизнь не расходует жертву или ресурс',()=>{const s=fixture({players:{p1:{health:1,pool:{'core:energy':5}}},board:{p1:['examples:blood_artificer','core:recruit']}}),before=JSON.stringify(s);const r=E.execute(s,{type:'ActivateAbility',actorId:'p1',source:find(s,'examples:blood_artificer'),abilityId:'blood_exchange',targets:{beneficiary:{playerId:'p1'}},costChoices:{offering:[find(s,'core:recruit')]}});assert.equal(r.error.code,'INSUFFICIENT_LIFE');assert.equal(JSON.stringify(s),before);});
  test('Оплата ровно оставшихся жизней законна и проигрывает',()=>{let s=fixture({players:{p1:{health:2,pool:{'core:energy':5}}},board:{p1:['examples:blood_artificer','core:recruit']}});s=exec(s,{type:'ActivateAbility',actorId:'p1',source:find(s,'examples:blood_artificer'),abilityId:'blood_exchange',targets:{beneficiary:{playerId:'p1'}},costChoices:{offering:[find(s,'core:recruit')]}});assert.equal(s.result.winner,'p2');assert.equal(s.stack.length,1);});
  test('Источник-существо сохраняет способность после жертвы себя',()=>{let s=fixture({board:{p1:['examples:dragon_apprentice']}});const a=E.getLegalActions(s,'p1').find(a=>a.type==='ActivateAbility');assert.ok(a);s=exec(s,E.materialize(a));assert.equal(s.stack.length,1);s=resolveTop(s);assert.ok(Object.values(s.instances).some(o=>o.isToken));});
  test('Источник выкладывается без стека только один раз за ход',()=>{let s=E.loadFixture({presetId:'duality_sources_v1',hand:{p1:['duality:light_well','duality:dark_well']}},content);s=exec(s,{type:'PlayResourceCard',actorId:'p1',card:find(s,'duality:light_well')});assert.equal(s.stack.length,0);assert.equal(E.execute(s,{type:'PlayResourceCard',actorId:'p1',card:find(s,'duality:dark_well')}).error.code,'SOURCE_LIMIT');});
  test('Производство немедленно, разворот источника не требуется ждать',()=>{let s=E.loadFixture({presetId:'duality_sources_v1',hand:{p1:['duality:light_well']}},content);s=exec(s,{type:'PlayResourceCard',actorId:'p1',card:find(s,'duality:light_well')});s=exec(s,{type:'ActivateAbility',actorId:'p1',source:find(s,'duality:light_well'),abilityId:'produce'});assert.equal(s.players.p1.pool['duality:light'],1);assert.equal(s.stack.length,0);});
  test('Свет/Тьма очищаются на границе шага, не при первом пасе',()=>{let s=E.loadFixture({presetId:'duality_sources_v1',players:{p1:{pool:{'duality:light':2}}}},content);s=pass(s);assert.equal(s.players.p1.pool['duality:light'],2);s=pass(s);assert.equal(s.players.p1.pool['duality:light'],0);});
  test('Точная цена + generic: проверка PaymentPlan',()=>{assert.deepEqual(E.paymentPlan({'duality:light':2,'duality:dark':2},{resources:{'duality:light':1},generic:2}),{'duality:light':1,'duality:dark':2});assert.throws(()=>E.paymentPlan({'duality:light':2},{resources:{'duality:dark':1}}));assert.throws(()=>E.paymentPlan({x:3},{generic:1},{x:2}));});
  test('Смена экономики не обесцвечивает цены и не допускает источники',()=>{assert.throws(()=>C.validateDeck(content.decks['duality:starter'],content,C.normalizeConfig({presetId:'automatic_energy_v1'},content)));});
  test('Исчезнувшая generation не становится новой целью',()=>{const s=fixture({board:{p1:['core:recruit']}}),r=find(s,'core:recruit');assert.equal(E.getObject(s,{...r,generation:r.generation+1}),undefined);});
  test('Прикреплённые чары выдают способность своему носителю',()=>{let s=E.loadFixture({presetId:'duality_sources_v1',players:{p1:{pool:{'duality:light':2}}},hand:{p1:['examples:renewal_enchantment']},board:{p1:['core:recruit']}},content);const host=find(s,'core:recruit');s=resolveTop(cast(s,'examples:renewal_enchantment',{attachmentHost:host}));const v=E.effectiveView(s)[host.instanceId+'@'+host.generation];assert.ok(v.abilities.some(a=>a.definitionId==='abilities:regeneration'));});
  test('Броня поглощает урон расходуемым запасом',()=>{let s=fixture({board:{p2:['examples:armored_construct']},hand:{p1:['core:spark']}});const target=find(s,'examples:armored_construct'),armor=E.getObject(s,target).armor;s=resolveTop(cast(s,'core:spark',{victim:target}));const o=E.getObject(s,target);assert.equal(o.armor,Math.max(0,armor-3));assert.equal(o.markedDamage,Math.max(0,3-armor));});
  test('Сила: общая usageGroup запрещает вторую активацию',()=>{let s=fixture({board:{p1:['examples:power_keeper']}});s=exec(s,{type:'ActivateAbility',actorId:'p1',source:find(s,'examples:power_keeper'),abilityId:'insight'});s=resolveTop(s);const r=E.execute(s,{type:'ActivateAbility',actorId:'p1',source:find(s,'examples:power_keeper'),abilityId:'insight'});assert.equal(r.error.code,'USAGE_LIMIT');});
  test('Возвращение с кладбища создаёт новую generation',()=>{let s=E.loadFixture({presetId:'duality_sources_v1',players:{p1:{pool:{'duality:dark':10}}},graveyard:{p1:['core:recruit']},hand:{p1:['examples:necromancers_call']}},content);const old=find(s,'core:recruit');const card=content.cards['examples:necromancers_call'];s=resolveTop(cast(s,card.id,{[card.targets[0].id]:old}));const o=Object.values(s.instances).find(o=>o.cardId==='core:recruit');assert.equal(o.zone,'battlefield');assert.ok(o.generation>old.generation);});
  test('Concede доступна вне приоритета',()=>{const s=fixture();assert.equal(exec(s,{type:'Concede',actorId:'p2'}).result.winner,'p1');});
  test('Save/load сохраняет весь снимок',()=>{const s=fixture({board:{p1:['core:recruit']}});assert.equal(E.hashState(E.loadGame(E.saveGame(s))),E.hashState(s));});
  test('Replay повторяет команды и конечный хеш',()=>{let s=fixture({hand:{p1:['core:spark']}});s=resolveTop(cast(s,'core:spark',{victim:{playerId:'p2'}}));assert.equal(E.hashState(E.replay(E.makeReplay(s))),E.hashState(s));});
  test('Публичный вид скрывает чужую руку и порядок колод',()=>{const s=E.createGame({},content,1),v=E.getPlayerView(s,'p1');assert.deepEqual(v.players.p2.hand,[]);assert.equal(v.players.p1.deck,undefined);assert.equal(v.rngState,undefined);assert.equal(v.instances,undefined);});
  test('Бот: решение не зависит от чужой скрытой руки',()=>{const s=E.createGame({},content,1),p=s.priorityPlayerId,a=E.getDecisionContext(s,p),b=structuredClone(s);b.players[p==='p1'?'p2':'p1'].hand.reverse();assert.deepEqual(B.chooseAction(a),B.chooseAction(E.getDecisionContext(b,p)));});
  test('Бот выбирает смертельный урон',()=>{const s=fixture({hand:{p1:['core:spark']},players:{p1:{pool:{'core:energy':5}},p2:{health:3}}}),d=B.chooseAction(E.getDecisionContext(s,'p1'));assert.equal(d.command.type,'CastCard');assert.equal(d.command.targets.victim.playerId,'p2');});
  test('Новый составной тип работает без изменения engine',()=>{const r=structuredClone(raw);r.cardTypes.push({id:'test:armored',extends:'types:creature',name:'Тест',components:{armor:{}}});r.cards.push({id:'test:unit',name:'Тест',typeId:'test:armored',cost:{generic:1},attack:2,health:3,armor:2});assert.ok(C.validateContent(r).cardTypes['test:armored'].capabilities.includes('combat_attacker'));});
  test('Удаление зависимости компонента отклоняется',()=>{const r=structuredClone(raw.cardTypes);r.push({id:'test:bad',name:'Тест',extends:'types:creature',removeComponents:['health']});assert.throws(()=>C.compileCardTypes(r));});
  test('Неизвестная операция отклоняется при загрузке',()=>{const r=structuredClone(raw);r.cards.find(c=>c.id==='core:spark').effects[0].type='eval';assert.throws(()=>C.validateContent(r));});
  test('DurationSpec требует объект',()=>{const r=structuredClone(raw);r.cards.find(c=>c.id==='core:rally').effects[0].duration='until_end_of_turn';assert.throws(()=>C.validateContent(r));});
  test('draw не принимает выбранное существо',()=>{const r=structuredClone(raw);r.cards.find(c=>c.id==='core:spark').effects=[{type:'draw',player:{selected:'victim'},amount:1}];assert.throws(()=>C.validateContent(r));});
  test('Переполнение выражения не превращается в перенос JS',()=>{const s=fixture();assert.throws(()=>E.evaluate(s,{type:'add',left:2147483647,right:1}));});
  test('Лимит поля нормализуется и проверяется',()=>{assert.equal(C.normalizeConfig({},content).limits.maxCreaturesPerPlayer,7);assert.throws(()=>C.normalizeConfig({limits:{maxCreaturesPerPlayer:33}},content));});

  test('Общие входные объекты fixture не связывают пулы игроков',()=>{const pool={'core:energy':10};let s=fixture({players:{p1:{pool},p2:{pool}},hand:{p1:['core:recruit']}});s=cast(s,'core:recruit');assert.equal(s.players.p1.pool['core:energy'],9);assert.equal(s.players.p2.pool['core:energy'],10);});
  test('Усталость увеличивается по попыткам добора',()=>{let s=fixture({board:{p1:['examples:power_keeper']}});s=exec(s,{type:'ActivateAbility',actorId:'p1',source:find(s,'examples:power_keeper'),abilityId:'insight'});s=resolveTop(s);assert.equal(s.players.p1.fatigue,2);assert.equal(s.players.p1.health,17);});
  test('Фишка исчезает после смерти, DeathRecord сохраняет снимок',()=>{let s=fixture({board:{p2:[{cardId:'tokens:red_dragon_2_2',isToken:true}]},hand:{p1:['core:spark']}});const r=find(s,'tokens:red_dragon_2_2');s=resolveTop(cast(s,'core:spark',{victim:r}));assert.equal(s.instances[r.instanceId],undefined);assert.equal(s.deaths[0].creatureSnapshot.isToken,true);});
  test('Вычисление читает текущую атаку, а после смерти источник-снимок',()=>{let s=fixture({board:{p1:['examples:variable_mage']},hand:{p2:['core:spark']}});s=exec(s,{type:'ActivateAbility',actorId:'p1',source:find(s,'examples:variable_mage'),abilityId:'double_strike',targets:{victim:{playerId:'p2'}}});s=pass(s);s=cast(s,'core:spark',{victim:find(s,'examples:variable_mage')});s=resolveTop(s);s=resolveTop(s);assert.equal(s.players.p2.health,16);});
  test('afterResolve считает смерти после checkpoint',()=>{let s=fixture({hand:{p1:['examples:plague_pulse']},board:{p2:['core:ember_bearer','core:ember_bearer']},players:{p1:{health:10,pool:{'core:energy':10}}}});s=resolveTop(cast(s,'examples:plague_pulse'));assert.equal(s.deaths.length,2);while(s.stack.length)s=resolveTop(s);assert.equal(s.players.p1.health,10);});
  test('Триггер с целью создаёт PendingDecision и сериализуется',()=>{const r=structuredClone(raw);r.cards.push({id:'test:targeted',name:'Адресный',typeId:'types:creature',cost:{generic:0},attack:1,health:2,abilities:[{id:'enter',kind:'triggered',trigger:'on_enter',targets:[{id:'victim',selector:'enemy_character',count:1}],effects:[{type:'damage',target:{selected:'victim'},amount:1}]}]});const c=C.validateContent(r);let s=E.loadFixture({hand:{p1:['test:targeted']}},c);s=resolveTop(cast(s,'test:targeted'));assert.equal(s.pendingDecision.playerId,'p1');s=E.loadGame(E.saveGame(s));assert.equal(E.execute(s,{type:'PassPriority',actorId:'p1'}).error.code,'PENDING_DECISION');s=exec(s,{type:'SubmitChoice',actorId:'p1',decisionId:s.pendingDecision.decisionId,targets:{victim:{playerId:'p2'}}});s=resolveTop(s);assert.equal(s.players.p2.health,19);});
  test('Жетон усиления переживает уход выдавшего источника',()=>{let s=fixture({hand:{p1:['examples:arrival_blessing'],p2:['core:spark']},board:{p1:['core:recruit']}});s=resolveTop(cast(s,'examples:arrival_blessing'));s=resolveTop(s);const recruit=find(s,'core:recruit');assert.equal(E.getObject(s,recruit).effectTokens.length,1);s=pass(s);s=resolveTop(cast(s,'core:spark',{victim:find(s,'examples:arrival_blessing')}));assert.equal(E.getObject(s,recruit).effectTokens.length,1);});
  test('Только игрок или существо в character, не носитель Силы',()=>{const s=fixture({board:{p2:['examples:power_keeper']}});assert.equal(E.query(s,{selector:'enemy_character'},{controller:{playerId:'p1'}}).length,1);assert.equal(E.query(s,{selector:'enemy_damageable'},{controller:{playerId:'p1'}}).length,2);});
  test('Атака носителя Силы расходует маркеры вместо здоровья игрока',()=>{let s=fixture({phase:'DECLARE_ATTACKERS',board:{p1:['core:sentinel'],p2:['examples:power_keeper']},combat:{combatId:'x',attackers:[],deaths:[]}});const target=find(s,'examples:power_keeper');s=exec(s,{type:'DeclareAttackers',actorId:'p1',attackers:[{attacker:find(s,'core:sentinel'),defender:target}]});s=resolveTop(s);s=exec(s,{type:'DeclareBlockers',actorId:'p2',blockers:[]});s=resolveTop(s);assert.equal(E.getObject(s,target).power,2);assert.equal(s.players.p2.health,20);});
  test('Новая аура приземляет и позже вошедших существ',()=>{let s=fixture({hand:{p1:['examples:grounding_weather','examples:marsh_drake']}});s=resolveTop(cast(s,'examples:grounding_weather'));s=resolveTop(cast(s,'examples:marsh_drake'));const drake=Object.values(s.instances).find(o=>o.cardId==='examples:marsh_drake');const v=E.effectiveView(s)[drake.instanceId+'@'+drake.generation];assert.equal(v.keywords.includes('flying'),false);});
  test('Подавление способности снимает её непрерывный бонус',()=>{let s=fixture({board:{p2:['examples:steadfast_guard']},hand:{p1:['examples:suppress_steadfast']}});const r=find(s,'examples:steadfast_guard');assert.equal(E.effectiveView(s)[r.instanceId+'@'+r.generation].maxHealth,4);s=resolveTop(cast(s,'examples:suppress_steadfast',{victim:r}));assert.equal(E.effectiveView(s)[r.instanceId+'@'+r.generation].maxHealth,2);});
  test('Невозможная объявленная цель отклоняется до оплаты',()=>{const s=fixture({hand:{p1:['core:spark']}}),before=JSON.stringify(s),r=E.execute(s,{type:'CastCard',actorId:'p1',card:find(s,'core:spark'),targets:{victim:{playerId:'p1'}}});assert.equal(r.error.code,'ILLEGAL_TARGET');assert.equal(JSON.stringify(s),before);});
  test('Необъявленная ссылка selected отклоняется при загрузке',()=>{const r=structuredClone(raw);r.cards.find(c=>c.id==='core:spark').effects[0].target={selected:'missing'};assert.throws(()=>C.validateContent(r));});
  test('Отрицательный урон в контенте отклоняется',()=>{const r=structuredClone(raw);r.cards.find(c=>c.id==='core:spark').effects[0].amount=-1;assert.throws(()=>C.validateContent(r));});


  test('draw для source-существа отклоняется статически',()=>{const r=structuredClone(raw);r.cards.find(c=>c.id==='core:healer').abilities[0].effects=[{type:'draw',player:{context:'source'},amount:1}];assert.throws(()=>C.validateContent(r));});
  test('Optional атака без fallback отклоняется статически',()=>{const r=structuredClone(raw);r.cards.find(c=>c.id==='examples:variable_mage').abilities[0].effects[0].amount={type:'read_property',object:{context:'source'},property:'attack',read:'effective'};assert.throws(()=>C.validateContent(r));});
  test('Необъявленные locals отклоняются до матча',()=>{const r=structuredClone(raw);r.cards.find(c=>c.id==='core:spark').effects[0].amount={type:'local',name:'missing'};assert.throws(()=>C.validateContent(r));});
  test('read_event вне события отклоняется до матча',()=>{const r=structuredClone(raw);r.cards.find(c=>c.id==='core:spark').effects[0].amount={type:'read_event',field:'amount'};assert.throws(()=>C.validateContent(r));});
  test('Слишком большой AST отклоняется до матча',()=>{const r=structuredClone(raw);r.cards.find(c=>c.id==='core:spark').effects=Array.from({length:100},()=>({type:'damage',target:{selected:'victim'},amount:1}));assert.throws(()=>C.validateContent(r));});


  test('Начальная раздача не публикует card_drawn',()=>{const s=E.createGame({},content,1);assert.equal(s.events.filter(e=>e.type==='card_drawn').length,0);});
  test('Шаблон карты раскрывает цену, materialize оставляет только платёж',()=>{const s=fixture({hand:{p1:['core:recruit']}}),t=E.getLegalActions(s,'p1').find(a=>a.type==='CastCard');assert.deepEqual(t.paymentCost,content.cards['core:recruit'].cost);assert.equal(E.materialize(t).paymentCost,undefined);assert.ok(E.execute(s,E.materialize(t)).ok);});
  test('Неизвестный ресурс даже с нулевым платежом отклоняется атомарно',()=>{const s=fixture({hand:{p1:['core:recruit']}}),command=E.materialize(E.getLegalActions(s,'p1').find(a=>a.type==='CastCard'));command.paymentPlan['bad:missing']=0;const r=E.execute(s,command);assert.equal(r.error.code,'INVALID_PAYMENT');assert.equal(r.state,s);assert.deepEqual(r.events,[]);});
  test('PaymentPlan позволяет выбрать ресурс для generic',()=>{const pool={'duality:light':3,'duality:dark':3};assert.deepEqual(E.paymentPlan(pool,{resources:{'duality:light':1},generic:2},{'duality:light':1,'duality:dark':2}),{'duality:light':1,'duality:dark':2});assert.throws(()=>E.paymentPlan(pool,{resources:{'duality:light':1},generic:2},{'duality:light':0,'duality:dark':3}));});
  test('Бот воспроизводит решение по собственному seed',()=>{const s=fixture({hand:{p1:['core:spark','core:recruit']}}),ctx=E.getDecisionContext(s,'p1'),before=E.hashState(s);assert.deepEqual(B.chooseAction({...ctx,policySeed:17}),B.chooseAction({...ctx,policySeed:17}));assert.equal(E.hashState(s),before);});
  test('Неизвестное поле CardDefinition отклоняется',()=>{const r=structuredClone(raw);r.cards[0].injected=true;assert.throws(()=>C.validateContent(r),/Неизвестное поле/);});
  test('Неизвестный keyword отклоняется',()=>{const r=structuredClone(raw);r.cards.find(c=>c.id==='core:recruit').keywords=['invented'];assert.throws(()=>C.validateContent(r));});
  test('Две библиотечные on_resolve имеют разные имена целей и единый frame',()=>{
    const r=structuredClone(raw);
    r.abilities.push({id:'test:repair',name:'Починка',stacking:'per_source',parameters:{},hostRequirements:{all:['one_shot','ability_host']},activeZones:['stack'],behaviors:[{id:'repair',kind:'on_resolve',targets:[{id:'target',selector:'friendly_creature',count:1}],effects:[{type:'heal',target:{selected:'target'},amount:5}]}]});
    r.cards.push({id:'test:modular',name:'Общий кадр',typeId:'types:instant',cost:{generic:0},targets:[{id:'target',selector:'friendly_creature',count:1}],effects:[{type:'damage',target:{selected:'target'},amount:5}],abilities:[{id:'repair_module',ref:'test:repair'}]});
    const c=C.validateContent(r);let s=E.loadFixture({hand:{p1:['test:modular']},board:{p1:['core:recruit']}},c),target=find(s,'core:recruit');
    const t=E.getLegalActions(s,'p1').find(a=>a.type==='CastCard');assert.equal(t.targets.length,2);assert.notEqual(t.targets[0].id,t.targets[1].id);
    s=exec(s,E.materialize(t));assert.equal(s.stack.length,1);s=resolveTop(s);assert.equal(E.getObject(s,target).zone,'battlefield');assert.equal(E.getObject(s,target).markedDamage,0);assert.equal(s.deaths.length,0);
  });

  test('Бюджет бота ограничивает фактическое число оценок',()=>{const s=fixture({hand:{p1:['core:spark','core:recruit']}}),context=E.getDecisionContext(s,'p1');const result=B.chooseAction({...context,budget:1});assert.equal(result.evaluated,1);assert.ok(E.execute(s,result.command).ok);});
  test('Немедленное производство не принимает жертвы и оплату жизнью',()=>{const r=structuredClone(raw);r.cards.find(c=>c.id==='duality:light_well').abilities[0].costs.push({type:'pay_life',amount:1});assert.throws(()=>C.validateContent(r),/только tap и spend_resource/);});
  const report={timestamp:new Date().toISOString(),passed:results.filter(t=>t.ok).length,failed:results.filter(t=>!t.ok).length,results};
  await mkdir(resolve(root,'artifacts'),{recursive:true});await writeFile(resolve(root,'artifacts/tests.json'),JSON.stringify(report,null,2));
  return report;
}
if(globalThis.process?.argv?.[1]&&resolve(globalThis.process.argv[1])===fileURLToPath(import.meta.url)){ const r=await runTests();console.log(JSON.stringify(r,null,2));globalThis.process.exitCode=r.failed?1:0;}
